# Path filters to include or exclude specific files/directories
reviews:
  path_filters:
    - '!dist/**'
    - '!node_modules/**'
    - '!build/**'
    - '!.next/**'
    - '!coverage/**'
# Examples you can add if needed:
#  - "!**/*.lock"        # ignore lockfiles
#  - "!public/assets/**" # ignore large static assets
