# Path filters to include or exclude specific files/directories
reviews:
  path_filters:
    - '!dist/**'
    - '!node_modules/**'
    - '!build/**'
    - '!.next/**'
    - '!coverage/**'
    - '!public/assets/**'
    - '!**/*.lock'
